# Generated by Django 3.1.12 on 2025-03-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_fraudulent',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
