# Generated by Django 3.1.12 on 2025-03-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_job_is_fraudulent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('IT', 'IT'), ('Marketing', 'Marketing'), ('Sales', 'Sales')], max_length=20),
        ),
    ]
