# Generated by Django 3.1.12 on 2025-03-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_auto_20250323_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_profile',
            field=models.TextField(blank=True),
        ),
    ]
