# Generated by Django 3.1.12 on 2025-03-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_job_benefits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_profile',
        ),
        migrations.RemoveField(
            model_name='job',
            name='department',
        ),
        migrations.RemoveField(
            model_name='job',
            name='function',
        ),
        migrations.RemoveField(
            model_name='job',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
    ]
